version: '3.8'
services:
  db:
    image: postgres
    hostname: 'postgres.container'
    container_name: 'pg-miab'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=messageinabottle
    ports:
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  server-air:
    image: cosmtrek/air
    working_dir: /server
    container_name: 'miab-server-air'
    ports:
      - "3030:3030"
    volumes:
      - ./server/:/server/

  frontend:
    container_name: 'miab-frontend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres-data:
